import type { Metadata } from "next";
import "././styles/globals.css";
import { AuthProvider } from "./context/AuthContext";
import { Roboto, Roboto_Mono } from "next/font/google";
import localFont from 'next/font/local';

const bulletproof = localFont({
  src: [
    {
      path: './fonts/Bulletproof_bb.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-bulletproof',
});

const geistSans = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const geistMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${bulletproof.variable} antialiased `}
        >
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
