import type { Metadata } from "next";
import "././styles/globals.css";
import localFont from 'next/font/local';
import { Noto_Sans_Arabic } from 'next/font/google';
import Providers from './providers';

const bulletproof = localFont({
  src: [
    {
      path: './fonts/Bulletproof_bb.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-bulletproof',
});
const popfun = localFont({
  src: [
    {
      path: './fonts/Popfun.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-popfun',
});
const Product_sans = localFont({
  src: [
    {
      path: './fonts/Product_sans.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-product_sans',
});

const notoArabic = Noto_Sans_Arabic({
  subsets: ['arabic'],
  weight: ['400', '700'],
  variable: '--font-arabic'
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { locale }, }: Readonly<{ children: React.ReactNode; params: { locale: string }; }>) {
  const isArabic = locale === "ar";
  return (
    <html lang="en">
      <body
        className={`
          ${notoArabic.className} 
          ${popfun.variable} 
          ${bulletproof.variable} 
          ${Product_sans.variable} 
          antialiased    
           ${notoArabic.variable} 
    ${isArabic ? "font-arabic" : "font-primary"}`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
