import type { Metadata } from "next";
import "././styles/globals.css";
import { AuthProvider } from "./context/AuthContext";
import localFont from 'next/font/local';
import Providers from './providers';

const bulletproof = localFont({
  src: [
    {
      path: './fonts/Bulletproof_bb.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-bulletproof',
});
const popfun = localFont({
  src: [
    {
      path: './fonts/Popfun.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-popfun',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`${popfun.variable} ${bulletproof.variable} antialiased `}>
          <Providers>{children}</Providers>
        </body>
      </AuthProvider>
    </html>
  );
}
